"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['UniqueFiles.py']
DATA_FILES = [
    ('static', ['static/bootstrap.bundle.min.js', 'static/bootstrap.min.js', 'static/bootstrap.min.css', 'static/jquery.js', 'static/sweetalert.js']),
    ('templates', ['templates/index.html'])
]
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
